server:
  port: 0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: publications-service
          uri: lb://publications-service
          predicates:
            - Path=/api/publications/**
          filters:
            - StripPrefix=2
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
    circuitbreaker:
      resilience4j:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/